### ISSUE TITLE
DNS resolution failed

### ISSUE THREAD

**Issue by RAbraham** [flaper87/pyhelm#74]
Hi,
I think I'm incorrectly setting TILLER_HOST. Please let me know what I'm doing wrong. Here is what I am doing:
```
> tiller_pod=pod/tiller-deploy-69f6c9d555-j6drx
> kubectl port-forward $tiller_pod 44134 -n kube-system
```

In my Python script

```
tiller_host = 'http://localhost:44134'
tiller = Tiller(tiller_host)
chart = ChartBuilder({"name": "nginx-ingress",
                           "source": {"type": "repo", "location": "https://kubernetes-charts.storage.googleapis.com"}})
tiller.install_release(chart.get_helm_chart(), dry_run=False, namespace='nginx-ingress') 
```

The error I get is:
```

/Users/rabraham/Documents/dev/fifteenrock/deployment/venv/bin/python /Users/rabraham/Documents/dev/fifteenrock/deployment/scripts/main.py
2019-06-15 21:03:58,563 - ChartBuilder - INFO - Cloning https://kubernetes-charts.storage.googleapis.com/ for release nginx-ingress
Traceback (most recent call last):
..
    tiller.install_release(chart.get_helm_chart(), dry_run=False, namespace='nginx-ingress')
  File "/Users/rabraham/Documents/dev/fifteenrock/deployment/venv/lib/python3.6/site-packages/pyhelm/tiller.py", line 201, in install_release
    metadata=self.metadata)
  File "/Users/rabraham/Documents/dev/fifteenrock/deployment/venv/lib/python3.6/site-packages/grpc/_channel.py", line 562, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/rabraham/Documents/dev/fifteenrock/deployment/venv/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed"
	debug_error_string = "{"created":"@1560647079.805992000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2715,"referenced_errors":[{"created":"@1560647079.805986000","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":335,"referenced_errors":[{"created":"@1560647079.805985000","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":327,"grpc_status":14,"referenced_errors":[{"created":"@1560647079.805897000","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":240,"referenced_errors":[{"created":"@1560647079.793972000","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":240}]}]}]}]}"
>



```

**Comment by yanivoliver** [comment]
Hi @RAbraham, are you able to install this chart successfully using the Helm CLI?

**Comment by RAbraham** [comment]
@yanivoliver Thanks for your quick response. Yes, I can install it with the helm cli with `helm install stable/nginx-ingress`

**Comment by miff2000** [comment]
Hi @RAbraham, can you try using `127.0.0.1` (no port or URL) for the value for `tiller_host` and report back whether that works? It should work

Also, if you could try setting to `localhost` and let us know, that'd be very useful for us

**Comment by RAbraham** [comment]
`localhost` worked. `127.0.0.1` did not work. Thanks!

**Comment by Privet-mir** [comment]
can you please tell how did you resolve this ? i am facing same error
